/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_2 (
    input clk,
    input [21:0] question,
    output reg [5:0] aluop,
    output reg [7:0] c,
    output reg [7:0] x,
    output reg [7:0] y
  );
  
  
  
  reg [7:0] a;
  
  reg [7:0] b;
  
  reg [5:0] alufn;
  
  reg [2:0] shift;
  
  always @* begin
    alufn = question[16+5-:6];
    aluop = alufn;
    a = question[8+7-:8];
    b = question[0+7-:8];
    x = a;
    y = b;
    
    case (alufn)
      6'h00: begin
        c = a + b;
      end
      6'h01: begin
        c = a - b;
      end
      6'h02: begin
        c = a * b;
      end
      6'h03: begin
        c = a / b;
      end
      6'h18: begin
        c = a & b;
      end
      6'h1e: begin
        c = a | b;
      end
      6'h16: begin
        c = a ^ b;
      end
      6'h1a: begin
        c = a;
      end
      6'h20: begin
        shift = b[0+2-:3];
        c = a << shift;
      end
      6'h21: begin
        shift = b[0+2-:3];
        c = a >> shift;
      end
      6'h23: begin
        shift = b[0+2-:3];
        c = $signed(a) >>> shift;
      end
      6'h33: begin
        c[0+0-:1] = (a == b);
        c[1+6-:7] = 7'h00;
      end
      6'h35: begin
        c[0+0-:1] = (a < b);
        c[1+6-:7] = 7'h00;
      end
      6'h37: begin
        c[0+0-:1] = (a <= b);
        c[1+6-:7] = 7'h00;
      end
      default: begin
        c = 8'h00;
      end
    endcase
  end
endmodule
